//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Progresses = new HashSet<Progress>();
        }
    
        public int StudentID { get; set; }
        public string Name { get; set; }
        public int GroupNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int SpecialityID { get; set; }
        public int RecordBookNumber { get; set; }
    
        public virtual ICollection<Progress> Progresses { get; set; }
        public virtual Speciality Speciality1 { get; set; }
    }
}
